import Foundation

extension AppLanguage {
    static var current: AppLanguage {
        let code = UserDefaults.standard.string(forKey: "settings.languageCode")
        return AppLanguage(rawValue: code ?? "") ?? .english
    }

    var locale: Locale {
        Locale(identifier: rawValue)
    }

    func text(_ key: L10n.Key) -> String {
        L10n.text(key, language: self)
    }

    func format(_ key: L10n.Key, _ arguments: CVarArg...) -> String {
        L10n.format(key, language: self, arguments: arguments)
    }
}

enum L10n {
    enum Key: CaseIterable, Hashable {
        case commonCancel
        case commonDone
        case commonSave
        case commonCreate
        case commonClose
        case commonNone
        case commonOK
        case commonDelete
        case commonEdit
        case commonOr

        case appTitle
        case homeEmptyTitle
        case homeEmptyDescription
        case homeToday
        case homeUpcoming
        case homeTomorrow
        case homeDayAfterTomorrow
        case homeExpired
        case homeNothingToday
        case homeNothingLater
        case homeSpeak
        case homeType
        case homeSettings
        case homeVoiceA11y
        case homeVoiceHint
        case homeTypeA11y

        case rowActionsHint
        case rowTimeUntil
        case rowDueOverdue
        case rowDueHour
        case rowDueToday
        case rowDueWeek
        case rowDueMonth
        case rowDueLater
        case rowEarlyMinutes
        case rowInMinutes
        case rowLessThanMinute
        case rowDueNow
        case rowOverdueMinutes
        case rowOverdueHoursMinutes
        case rowOverdueHours
        case rowNextOccurrence
        case rowDayAndTime
        case rowCountdownAndTime

        case repeatOnce
        case repeatDaily
        case repeatWeekly
        case repeatMonthly

        case voiceListening
        case voiceProcessing
        case voiceSummarizing
        case voiceCreated
        case voiceUpdated
        case voiceFailed
        case voiceListeningHint
        case voiceProcessingHint
        case voiceErrorNoTranscript
        case voiceErrorNoTime
        case voiceErrorPermission
        case voiceErrorEmptyTitle
        case voiceErrorPermissions
        case voiceErrorUnavailable
        case voiceErrorNoSpeech
        case voiceErrorMicrophone

        case confirmationTask
        case confirmationTitlePlaceholder
        case confirmationReminderTime
        case confirmationRepeat

        case alertReminder
        case alertGotIt
        case alertSnooze
        case alertSnoozeAction
        case alertSpeech

        case paywallTitle
        case paywallDescription
        case paywallRestore
        case paywallClose
        case paywallUnlockForever
        case paywallUnlockPrice

        case purchaseNotAvailable
        case purchasePending

        case settingsTitle
        case settingsLanguage
        case settingsAppLanguage
        case settingsLanguageFooter
        case settingsAlertStyle
        case settingsVoiceReading
        case settingsHapticPulse
        case settingsScreenFlash
        case settingsStrike
        case settingsEarlyMinutes
        case settingsVoiceVolume
        case settingsPrivacy
        case settingsClearAll
        case settingsPrivacyFooter
        case settingsVersion
        case settingsClearTitle
        case settingsDeleteAll
        case settingsClearMessage

        case addTitle
        case addSaving
        case addNotificationsRequired
        case addOpenSettings
        case addNotificationMessage
        case addSpeakOrType
        case addParseSentence
        case addParsed
        case addListening
        case addReminderTitle
        case addNoteOptional
        case addWhatRemember
        case addRemindAt
        case addWhen
        case addEndOn
        case addRepeatOnceFooter
        case addRepeatFooter
        case addStrikeEvery
        case addEarlyReminder
        case addMinutes5
        case addMinutes10
        case addMinutes15
        case addPreviewVoice
        case addStopRecording
        case addStartVoiceInput
        case addPreviewSentence

        case notificationEarlyBody
        case notificationEarlySpeech
    }

    static func text(_ key: Key, language: AppLanguage) -> String {
        table(for: language)[key] ?? english[key] ?? String(describing: key)
    }

    static func format(
        _ key: Key,
        language: AppLanguage,
        arguments: [CVarArg]
    ) -> String {
        String(
            format: text(key, language: language),
            locale: language.locale,
            arguments: arguments
        )
    }

    static func isComplete(for language: AppLanguage) -> Bool {
        table(for: language).count == Key.allCases.count
    }

    private static func table(for language: AppLanguage) -> [Key: String] {
        switch language {
        case .english: english
        case .japanese: japanese
        case .korean: korean
        case .french: french
        case .german: german
        case .turkish: turkish
        case .chinese: chinese
        case .spanish: spanish
        case .portuguese: portuguese
        case .russian: russian
        }
    }

    private static let english: [Key: String] = [
        .commonCancel: "Cancel",
        .commonDone: "Done",
        .commonSave: "Save",
        .commonCreate: "Create",
        .commonClose: "Close",
        .commonNone: "None",
        .commonOK: "OK",
        .commonDelete: "Delete",
        .commonEdit: "Edit",
        .commonOr: "or",
        .appTitle: "In Case I Forget",
        .homeEmptyTitle: "Nothing scheduled",
        .homeEmptyDescription: "Speak or type a one-line reminder.",
        .homeToday: "Today",
        .homeUpcoming: "Upcoming",
        .homeTomorrow: "Tomorrow",
        .homeDayAfterTomorrow: "Day after tomorrow",
        .homeExpired: "Expired",
        .homeNothingToday: "Nothing today",
        .homeNothingLater: "Nothing later",
        .homeSpeak: "Speak",
        .homeType: "Type",
        .homeSettings: "Settings",
        .homeVoiceA11y: "Create reminder by voice",
        .homeVoiceHint: "Press and hold to speak",
        .homeTypeA11y: "Type a reminder",
        .rowActionsHint: "Opens edit and delete actions",
        .rowTimeUntil: "Time until reminder",
        .rowDueOverdue: "Due now or overdue",
        .rowDueHour: "Due within an hour",
        .rowDueToday: "Due today",
        .rowDueWeek: "Due this week",
        .rowDueMonth: "Due within a month",
        .rowDueLater: "More than a month away",
        .rowEarlyMinutes: "Early %d min",
        .rowInMinutes: "in %d min",
        .rowLessThanMinute: "in less than a minute",
        .rowDueNow: "Due now",
        .rowOverdueMinutes: "overdue %d min",
        .rowOverdueHoursMinutes: "overdue %d hr %d min",
        .rowOverdueHours: "overdue %d hr",
        .rowNextOccurrence: "Next: %@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "Once",
        .repeatDaily: "Daily",
        .repeatWeekly: "Weekly",
        .repeatMonthly: "Monthly",
        .voiceListening: "Listening…",
        .voiceProcessing: "Converting to text",
        .voiceSummarizing: "Summarizing task",
        .voiceCreated: "Reminder created",
        .voiceUpdated: "Changes saved",
        .voiceFailed: "Not completed",
        .voiceListeningHint: "Say your reminder, then release",
        .voiceProcessingHint: "Converting your speech to text",
        .voiceErrorNoTranscript: "I didn't catch that. Hold Speak and try again.",
        .voiceErrorNoTime: "I couldn't find a clear reminder time. Please be more specific.",
        .voiceErrorPermission: "Notifications are required. Allow them in Settings to create reminders.",
        .voiceErrorEmptyTitle: "The task title cannot be empty.",
        .voiceErrorPermissions: "Microphone and speech recognition permission are required.",
        .voiceErrorUnavailable: "Speech recognition is unavailable for this language. You can still type.",
        .voiceErrorNoSpeech: "No speech was captured.",
        .voiceErrorMicrophone: "Unable to start the microphone.",
        .confirmationTask: "Task",
        .confirmationTitlePlaceholder: "Reminder title",
        .confirmationReminderTime: "Reminder time",
        .confirmationRepeat: "Repeat",
        .alertReminder: "Reminder",
        .alertGotIt: "Got it",
        .alertSnooze: "Snooze 10 min",
        .alertSnoozeAction: "10 min later",
        .alertSpeech: "It's %1$@. %2$@. Don't forget.",
        .paywallTitle: "Unlock Repeating Reminders",
        .paywallDescription: "Pay once and keep daily, weekly and monthly reminders forever.",
        .paywallRestore: "Restore Purchase",
        .paywallClose: "Close",
        .paywallUnlockForever: "Unlock Forever",
        .paywallUnlockPrice: "Unlock Forever · %@",
        .purchaseNotAvailable: "The Pro product is not available yet.",
        .purchasePending: "The purchase is pending approval.",
        .settingsTitle: "Settings",
        .settingsLanguage: "Language",
        .settingsAppLanguage: "App language",
        .settingsLanguageFooter: "Used for the interface, speech recognition and spoken reminders.",
        .settingsAlertStyle: "Alert style",
        .settingsVoiceReading: "Voice reading",
        .settingsHapticPulse: "Haptic pulse",
        .settingsScreenFlash: "Screen flash",
        .settingsStrike: "Strike reminders",
        .settingsEarlyMinutes: "Early reminder %d min",
        .settingsVoiceVolume: "Voice volume",
        .settingsPrivacy: "Privacy",
        .settingsClearAll: "Clear all local data",
        .settingsPrivacyFooter: "This removes reminders, scheduled notifications and generated files. No account is used.",
        .settingsVersion: "Version",
        .settingsClearTitle: "Clear everything?",
        .settingsDeleteAll: "Delete all",
        .settingsClearMessage: "All reminders will be permanently deleted from this device.",
        .addTitle: "New Reminder",
        .addSaving: "Saving…",
        .addNotificationsRequired: "Notifications are required",
        .addOpenSettings: "Open Settings",
        .addNotificationMessage: "Allow notifications so reminders can reach you at the right time.",
        .addSpeakOrType: "Speak or type…",
        .addParseSentence: "Parse sentence",
        .addParsed: "Parsed: %@",
        .addListening: "Listening…",
        .addReminderTitle: "Reminder title",
        .addNoteOptional: "Note (optional)",
        .addWhatRemember: "What should we remember?",
        .addRemindAt: "Remind at",
        .addWhen: "When",
        .addEndOn: "End on",
        .addRepeatOnceFooter: "One-time reminders are removed one day after they expire.",
        .addRepeatFooter: "Use an end date for tasks like medication for 7 days.",
        .addStrikeEvery: "Strike again every 30 seconds",
        .addEarlyReminder: "Early reminder",
        .addMinutes5: "5 minutes",
        .addMinutes10: "10 minutes",
        .addMinutes15: "15 minutes",
        .addPreviewVoice: "Preview voice",
        .addStopRecording: "Stop recording",
        .addStartVoiceInput: "Start voice input",
        .addPreviewSentence: "This is a reminder preview.",
        .notificationEarlyBody: "%@ (in %d min)",
        .notificationEarlySpeech: "Your reminder is at %1$@, in %2$d minutes. %3$@."
    ]

    private static let chinese: [Key: String] = [
        .commonCancel: "取消",
        .commonDone: "完成",
        .commonSave: "保存",
        .commonCreate: "创建",
        .commonClose: "关闭",
        .commonNone: "无",
        .commonOK: "好",
        .commonDelete: "删除",
        .commonEdit: "重编辑",
        .commonOr: "or",
        .appTitle: "万一我忘了",
        .homeEmptyTitle: "还没有提醒",
        .homeEmptyDescription: "按住说话或打字，记下一句话提醒。",
        .homeToday: "今天",
        .homeUpcoming: "以后",
        .homeTomorrow: "明天",
        .homeDayAfterTomorrow: "后天",
        .homeExpired: "已过期",
        .homeNothingToday: "今天没有提醒",
        .homeNothingLater: "之后没有提醒",
        .homeSpeak: "说话",
        .homeType: "打字",
        .homeSettings: "设置",
        .homeVoiceA11y: "用语音创建提醒",
        .homeVoiceHint: "按住说话",
        .homeTypeA11y: "输入提醒",
        .rowActionsHint: "打开重编辑和删除操作",
        .rowTimeUntil: "距离提醒时间",
        .rowDueOverdue: "现在到期或已过期",
        .rowDueHour: "一小时内",
        .rowDueToday: "今天",
        .rowDueWeek: "本周",
        .rowDueMonth: "一个月内",
        .rowDueLater: "一个月以后",
        .rowEarlyMinutes: "提前 %d 分钟",
        .rowInMinutes: "%d分钟后",
        .rowLessThanMinute: "不到1分钟",
        .rowDueNow: "现在到期",
        .rowOverdueMinutes: "已过期%d分钟",
        .rowOverdueHoursMinutes: "已过期%d小时%d分钟",
        .rowOverdueHours: "已过期%d小时",
        .rowNextOccurrence: "下一次：%@",
        .rowDayAndTime: "%1$@%2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "一次",
        .repeatDaily: "每天",
        .repeatWeekly: "每周",
        .repeatMonthly: "每月",
        .voiceListening: "正在聆听",
        .voiceProcessing: "正在转成文字",
        .voiceSummarizing: "正在概括任务",
        .voiceCreated: "已创建提醒",
        .voiceUpdated: "已保存修改",
        .voiceFailed: "没有完成",
        .voiceListeningHint: "请说出提醒内容，松开结束",
        .voiceProcessingHint: "正在把语音转成文字",
        .voiceErrorNoTranscript: "没有听清，请按住“说话”再说一次。",
        .voiceErrorNoTime: "没有识别出明确的提醒时间，请说得具体一些。",
        .voiceErrorPermission: "需要通知权限才能创建提醒，请到系统设置中允许通知。",
        .voiceErrorEmptyTitle: "任务标题不能为空。",
        .voiceErrorPermissions: "需要麦克风和语音识别权限。",
        .voiceErrorUnavailable: "当前语言暂时无法使用语音识别，你仍然可以打字。",
        .voiceErrorNoSpeech: "没有捕捉到语音。",
        .voiceErrorMicrophone: "无法启动麦克风。",
        .confirmationTask: "任务",
        .confirmationTitlePlaceholder: "提醒标题",
        .confirmationReminderTime: "提醒时间",
        .confirmationRepeat: "重复",
        .alertReminder: "提醒",
        .alertGotIt: "收到",
        .alertSnooze: "10 分钟后再提醒",
        .alertSnoozeAction: "10 分钟后",
        .alertSpeech: "现在是%1$@。%2$@。别忘了。",
        .paywallTitle: "解锁重复提醒",
        .paywallDescription: "一次购买，永久使用每日、每周和每月重复提醒。",
        .paywallRestore: "恢复购买",
        .paywallClose: "关闭",
        .paywallUnlockForever: "永久解锁",
        .paywallUnlockPrice: "永久解锁 · %@",
        .purchaseNotAvailable: "专业版商品暂时不可用。",
        .purchasePending: "购买正在等待批准。",
        .settingsTitle: "设置",
        .settingsLanguage: "语言",
        .settingsAppLanguage: "App 语言",
        .settingsLanguageFooter: "用于界面、语音识别和提醒播报。",
        .settingsAlertStyle: "提醒方式",
        .settingsVoiceReading: "语音播报",
        .settingsHapticPulse: "触感脉冲",
        .settingsScreenFlash: "屏幕闪光",
        .settingsStrike: "强袭提醒",
        .settingsEarlyMinutes: "提前 %d 分钟提醒",
        .settingsVoiceVolume: "语音音量",
        .settingsPrivacy: "隐私",
        .settingsClearAll: "清除所有本地数据",
        .settingsPrivacyFooter: "会删除提醒、已排程通知和生成的文件。不需要账号。",
        .settingsVersion: "版本",
        .settingsClearTitle: "清除全部内容？",
        .settingsDeleteAll: "全部删除",
        .settingsClearMessage: "所有提醒都会从这台设备永久删除。",
        .addTitle: "新建提醒",
        .addSaving: "正在保存…",
        .addNotificationsRequired: "需要通知权限",
        .addOpenSettings: "打开设置",
        .addNotificationMessage: "允许通知，提醒才能在正确的时间找到你。",
        .addSpeakOrType: "说话或打字…",
        .addParseSentence: "解析这句话",
        .addParsed: "已解析：%@",
        .addListening: "正在聆听…",
        .addReminderTitle: "提醒标题",
        .addNoteOptional: "备注（可选）",
        .addWhatRemember: "要记住什么？",
        .addRemindAt: "提醒时间",
        .addWhen: "时间",
        .addEndOn: "结束于",
        .addRepeatOnceFooter: "一次性提醒会在过期一天后自动清除。",
        .addRepeatFooter: "像连续 7 天服药这样的任务，可以设置结束日期。",
        .addStrikeEvery: "每 30 秒再次强袭",
        .addEarlyReminder: "提前提醒",
        .addMinutes5: "5 分钟",
        .addMinutes10: "10 分钟",
        .addMinutes15: "15 分钟",
        .addPreviewVoice: "试听语音",
        .addStopRecording: "停止录音",
        .addStartVoiceInput: "开始语音输入",
        .addPreviewSentence: "这是一条提醒预览。",
        .notificationEarlyBody: "%@（%d 分钟后）",
        .notificationEarlySpeech: "提醒时间是%1$@，还有%2$d分钟。%3$@。"
    ]

    private static let japanese: [Key: String] = [
        .commonCancel: "キャンセル",
        .commonDone: "完了",
        .commonSave: "保存",
        .commonCreate: "作成",
        .commonClose: "閉じる",
        .commonNone: "なし",
        .commonOK: "OK",
        .commonDelete: "削除",
        .commonEdit: "編集",
        .commonOr: "or",
        .appTitle: "忘れたときのために",
        .homeEmptyTitle: "予定されたリマインダーはありません",
        .homeEmptyDescription: "話すか入力して、一行のリマインダーを作成できます。",
        .homeToday: "今日",
        .homeUpcoming: "今後",
        .homeTomorrow: "明日",
        .homeDayAfterTomorrow: "明後日",
        .homeExpired: "期限切れ",
        .homeNothingToday: "今日はありません",
        .homeNothingLater: "この後の予定はありません",
        .homeSpeak: "話す",
        .homeType: "入力",
        .homeSettings: "設定",
        .homeVoiceA11y: "音声でリマインダーを作成",
        .homeVoiceHint: "長押しして話す",
        .homeTypeA11y: "リマインダーを入力",
        .rowActionsHint: "編集と削除の操作を開く",
        .rowTimeUntil: "リマインダーまでの時間",
        .rowDueOverdue: "期限が近いか過ぎています",
        .rowDueHour: "1時間以内",
        .rowDueToday: "今日",
        .rowDueWeek: "今週",
        .rowDueMonth: "1か月以内",
        .rowDueLater: "1か月以上先",
        .rowEarlyMinutes: "%d分前に通知",
        .rowInMinutes: "%d分後",
        .rowLessThanMinute: "1分未満",
        .rowDueNow: "現在が期限",
        .rowOverdueMinutes: "%d分過ぎ",
        .rowOverdueHoursMinutes: "%d時間%d分過ぎ",
        .rowOverdueHours: "%d時間過ぎ",
        .rowNextOccurrence: "次回：%@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "1回",
        .repeatDaily: "毎日",
        .repeatWeekly: "毎週",
        .repeatMonthly: "毎月",
        .voiceListening: "聞き取り中",
        .voiceProcessing: "文字に変換中",
        .voiceSummarizing: "タスクを要約中",
        .voiceCreated: "リマインダーを作成しました",
        .voiceUpdated: "変更を保存しました",
        .voiceFailed: "完了できませんでした",
        .voiceListeningHint: "リマインダーを話してから離してください",
        .voiceProcessingHint: "音声を文字に変換しています",
        .voiceErrorNoTranscript: "聞き取れませんでした。「話す」を長押しして再試行してください。",
        .voiceErrorNoTime: "明確なリマインダー時間を認識できませんでした。もう少し具体的に話してください。",
        .voiceErrorPermission: "リマインダーの作成には通知の許可が必要です。設定で許可してください。",
        .voiceErrorEmptyTitle: "タスク名を空にはできません。",
        .voiceErrorPermissions: "マイクと音声認識の許可が必要です。",
        .voiceErrorUnavailable: "この言語では音声認識を利用できません。入力は引き続き使えます。",
        .voiceErrorNoSpeech: "音声を取得できませんでした。",
        .voiceErrorMicrophone: "マイクを開始できません。",
        .confirmationTask: "タスク",
        .confirmationTitlePlaceholder: "リマインダー名",
        .confirmationReminderTime: "リマインダー時間",
        .confirmationRepeat: "繰り返し",
        .alertReminder: "リマインダー",
        .alertGotIt: "了解",
        .alertSnooze: "10分後に再通知",
        .alertSnoozeAction: "10分後",
        .alertSpeech: "%1$@です。%2$@。忘れないでください。",
        .paywallTitle: "繰り返しリマインダーを解除",
        .paywallDescription: "一度の購入で、毎日・毎週・毎月のリマインダーを永久に使えます。",
        .paywallRestore: "購入を復元",
        .paywallClose: "閉じる",
        .paywallUnlockForever: "永久に解除",
        .paywallUnlockPrice: "永久に解除 · %@",
        .purchaseNotAvailable: "Pro商品はまだ利用できません。",
        .purchasePending: "購入は承認待ちです。",
        .settingsTitle: "設定",
        .settingsLanguage: "言語",
        .settingsAppLanguage: "アプリの言語",
        .settingsLanguageFooter: "画面、音声認識、読み上げに使用します。",
        .settingsAlertStyle: "通知スタイル",
        .settingsVoiceReading: "音声読み上げ",
        .settingsHapticPulse: "触覚",
        .settingsScreenFlash: "画面フラッシュ",
        .settingsStrike: "再通知",
        .settingsEarlyMinutes: "%d分前に通知",
        .settingsVoiceVolume: "音量",
        .settingsPrivacy: "プライバシー",
        .settingsClearAll: "ローカルデータをすべて消去",
        .settingsPrivacyFooter: "リマインダー、予約済み通知、生成ファイルを削除します。アカウントは不要です。",
        .settingsVersion: "バージョン",
        .settingsClearTitle: "すべて消去しますか？",
        .settingsDeleteAll: "すべて削除",
        .settingsClearMessage: "すべてのリマインダーがこの端末から完全に削除されます。",
        .addTitle: "新しいリマインダー",
        .addSaving: "保存中…",
        .addNotificationsRequired: "通知が必要です",
        .addOpenSettings: "設定を開く",
        .addNotificationMessage: "時間どおりに知らせるため、通知を許可してください。",
        .addSpeakOrType: "話すか入力…",
        .addParseSentence: "文章を解析",
        .addParsed: "解析済み：%@",
        .addListening: "聞き取り中…",
        .addReminderTitle: "リマインダー名",
        .addNoteOptional: "メモ（任意）",
        .addWhatRemember: "何を覚えますか？",
        .addRemindAt: "通知時間",
        .addWhen: "日時",
        .addEndOn: "終了日",
        .addRepeatOnceFooter: "1回のリマインダーは期限から1日後に削除されます。",
        .addRepeatFooter: "7日間の服薬などには終了日を設定できます。",
        .addStrikeEvery: "30秒ごとに再通知",
        .addEarlyReminder: "事前通知",
        .addMinutes5: "5分",
        .addMinutes10: "10分",
        .addMinutes15: "15分",
        .addPreviewVoice: "音声を試聴",
        .addStopRecording: "録音を停止",
        .addStartVoiceInput: "音声入力を開始",
        .addPreviewSentence: "これはリマインダーのプレビューです。",
        .notificationEarlyBody: "%@（%d分後）",
        .notificationEarlySpeech: "リマインダーは%1$@、%2$d分後です。%3$@。"
    ]

    private static let korean: [Key: String] = [
        .commonCancel: "취소",
        .commonDone: "완료",
        .commonSave: "저장",
        .commonCreate: "만들기",
        .commonClose: "닫기",
        .commonNone: "없음",
        .commonOK: "확인",
        .commonDelete: "삭제",
        .commonEdit: "편집",
        .commonOr: "or",
        .appTitle: "혹시 잊을까 봐",
        .homeEmptyTitle: "예정된 알림이 없습니다",
        .homeEmptyDescription: "말하거나 입력해서 한 줄 알림을 만드세요.",
        .homeToday: "오늘",
        .homeUpcoming: "예정",
        .homeTomorrow: "내일",
        .homeDayAfterTomorrow: "모레",
        .homeExpired: "만료됨",
        .homeNothingToday: "오늘은 없습니다",
        .homeNothingLater: "나중 일정이 없습니다",
        .homeSpeak: "말하기",
        .homeType: "입력",
        .homeSettings: "설정",
        .homeVoiceA11y: "음성으로 알림 만들기",
        .homeVoiceHint: "길게 눌러 말하기",
        .homeTypeA11y: "알림 입력",
        .rowActionsHint: "편집 및 삭제 메뉴 열기",
        .rowTimeUntil: "알림까지 남은 시간",
        .rowDueOverdue: "곧 또는 기한 지남",
        .rowDueHour: "1시간 이내",
        .rowDueToday: "오늘",
        .rowDueWeek: "이번 주",
        .rowDueMonth: "한 달 이내",
        .rowDueLater: "한 달 이상 후",
        .rowEarlyMinutes: "%d분 전",
        .rowInMinutes: "%d분 후",
        .rowLessThanMinute: "1분 이내",
        .rowDueNow: "지금 만료",
        .rowOverdueMinutes: "%d분 지남",
        .rowOverdueHoursMinutes: "%d시간 %d분 지남",
        .rowOverdueHours: "%d시간 지남",
        .rowNextOccurrence: "다음: %@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "한 번",
        .repeatDaily: "매일",
        .repeatWeekly: "매주",
        .repeatMonthly: "매월",
        .voiceListening: "듣는 중",
        .voiceProcessing: "텍스트로 변환 중",
        .voiceSummarizing: "작업 요약 중",
        .voiceCreated: "알림을 만들었습니다",
        .voiceUpdated: "변경 사항을 저장했습니다",
        .voiceFailed: "완료하지 못했습니다",
        .voiceListeningHint: "알림 내용을 말한 뒤 손을 떼세요",
        .voiceProcessingHint: "음성을 텍스트로 변환 중입니다",
        .voiceErrorNoTranscript: "잘 듣지 못했습니다. 말하기를 길게 눌러 다시 시도하세요.",
        .voiceErrorNoTime: "명확한 알림 시간을 찾지 못했습니다. 더 구체적으로 말해 주세요.",
        .voiceErrorPermission: "알림을 만들려면 알림 권한이 필요합니다. 설정에서 허용하세요.",
        .voiceErrorEmptyTitle: "작업 제목은 비워 둘 수 없습니다.",
        .voiceErrorPermissions: "마이크와 음성 인식 권한이 필요합니다.",
        .voiceErrorUnavailable: "이 언어에서는 음성 인식을 사용할 수 없습니다. 입력은 계속 사용할 수 있습니다.",
        .voiceErrorNoSpeech: "음성을 감지하지 못했습니다.",
        .voiceErrorMicrophone: "마이크를 시작할 수 없습니다.",
        .confirmationTask: "작업",
        .confirmationTitlePlaceholder: "알림 제목",
        .confirmationReminderTime: "알림 시간",
        .confirmationRepeat: "반복",
        .alertReminder: "알림",
        .alertGotIt: "확인",
        .alertSnooze: "10분 후 다시 알림",
        .alertSnoozeAction: "10분 후",
        .alertSpeech: "%1$@입니다. %2$@. 잊지 마세요.",
        .paywallTitle: "반복 알림 잠금 해제",
        .paywallDescription: "한 번 결제하면 매일, 매주, 매월 반복 알림을 계속 사용할 수 있습니다.",
        .paywallRestore: "구매 복원",
        .paywallClose: "닫기",
        .paywallUnlockForever: "영구 잠금 해제",
        .paywallUnlockPrice: "영구 잠금 해제 · %@",
        .purchaseNotAvailable: "Pro 상품을 아직 사용할 수 없습니다.",
        .purchasePending: "구매 승인을 기다리는 중입니다.",
        .settingsTitle: "설정",
        .settingsLanguage: "언어",
        .settingsAppLanguage: "앱 언어",
        .settingsLanguageFooter: "화면, 음성 인식, 음성 알림에 사용됩니다.",
        .settingsAlertStyle: "알림 방식",
        .settingsVoiceReading: "음성 읽기",
        .settingsHapticPulse: "진동",
        .settingsScreenFlash: "화면 깜박임",
        .settingsStrike: "강한 반복 알림",
        .settingsEarlyMinutes: "%d분 전 알림",
        .settingsVoiceVolume: "음량",
        .settingsPrivacy: "개인정보",
        .settingsClearAll: "모든 로컬 데이터 삭제",
        .settingsPrivacyFooter: "알림, 예약된 알림, 생성 파일을 삭제합니다. 계정은 필요하지 않습니다.",
        .settingsVersion: "버전",
        .settingsClearTitle: "모두 삭제할까요?",
        .settingsDeleteAll: "모두 삭제",
        .settingsClearMessage: "모든 알림이 이 기기에서 영구 삭제됩니다.",
        .addTitle: "새 알림",
        .addSaving: "저장 중…",
        .addNotificationsRequired: "알림 권한이 필요합니다",
        .addOpenSettings: "설정 열기",
        .addNotificationMessage: "제때 알림을 받으려면 알림을 허용하세요.",
        .addSpeakOrType: "말하거나 입력…",
        .addParseSentence: "문장 분석",
        .addParsed: "분석됨: %@",
        .addListening: "듣는 중…",
        .addReminderTitle: "알림 제목",
        .addNoteOptional: "메모(선택)",
        .addWhatRemember: "무엇을 기억할까요?",
        .addRemindAt: "알림 시간",
        .addWhen: "시간",
        .addEndOn: "종료일",
        .addRepeatOnceFooter: "일회성 알림은 만료 후 하루 뒤에 삭제됩니다.",
        .addRepeatFooter: "7일간 복약 같은 작업에는 종료일을 설정할 수 있습니다.",
        .addStrikeEvery: "30초마다 다시 알림",
        .addEarlyReminder: "미리 알림",
        .addMinutes5: "5분",
        .addMinutes10: "10분",
        .addMinutes15: "15분",
        .addPreviewVoice: "음성 미리 듣기",
        .addStopRecording: "녹음 중지",
        .addStartVoiceInput: "음성 입력 시작",
        .addPreviewSentence: "이것은 알림 미리보기입니다.",
        .notificationEarlyBody: "%@(%d분 후)",
        .notificationEarlySpeech: "알림은 %1$@, %2$d분 후입니다. %3$@."
    ]

    private static let french: [Key: String] = [
        .commonCancel: "Annuler",
        .commonDone: "Terminé",
        .commonSave: "Enregistrer",
        .commonCreate: "Créer",
        .commonClose: "Fermer",
        .commonNone: "Aucun",
        .commonOK: "OK",
        .commonDelete: "Supprimer",
        .commonEdit: "Modifier",
        .commonOr: "ou",
        .appTitle: "Au cas où j'oublie",
        .homeEmptyTitle: "Aucun rappel prévu",
        .homeEmptyDescription: "Parlez ou saisissez un rappel en une ligne.",
        .homeToday: "Aujourd'hui",
        .homeUpcoming: "À venir",
        .homeTomorrow: "Demain",
        .homeDayAfterTomorrow: "Après-demain",
        .homeExpired: "Expiré",
        .homeNothingToday: "Rien aujourd'hui",
        .homeNothingLater: "Rien plus tard",
        .homeSpeak: "Parler",
        .homeType: "Saisir",
        .homeSettings: "Réglages",
        .homeVoiceA11y: "Créer un rappel à la voix",
        .homeVoiceHint: "Maintenir pour parler",
        .homeTypeA11y: "Saisir un rappel",
        .rowActionsHint: "Ouvre les actions de modification et suppression",
        .rowTimeUntil: "Temps avant le rappel",
        .rowDueOverdue: "Bientôt ou en retard",
        .rowDueHour: "Dans moins d'une heure",
        .rowDueToday: "Aujourd'hui",
        .rowDueWeek: "Cette semaine",
        .rowDueMonth: "Dans moins d'un mois",
        .rowDueLater: "Dans plus d’un mois",
        .rowEarlyMinutes: "%d min avant",
        .rowInMinutes: "dans %d min",
        .rowLessThanMinute: "dans moins d’une minute",
        .rowDueNow: "Échéance maintenant",
        .rowOverdueMinutes: "en retard de %d min",
        .rowOverdueHoursMinutes: "en retard de %d h %d min",
        .rowOverdueHours: "en retard de %d h",
        .rowNextOccurrence: "Suivant : %@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "Une fois",
        .repeatDaily: "Tous les jours",
        .repeatWeekly: "Chaque semaine",
        .repeatMonthly: "Chaque mois",
        .voiceListening: "Écoute en cours",
        .voiceProcessing: "Conversion en texte",
        .voiceSummarizing: "Résumé de la tâche",
        .voiceCreated: "Rappel créé",
        .voiceUpdated: "Modifications enregistrées",
        .voiceFailed: "Non terminé",
        .voiceListeningHint: "Dites votre rappel puis relâchez",
        .voiceProcessingHint: "Conversion de votre voix en texte",
        .voiceErrorNoTranscript: "Je n'ai pas compris. Maintenez Parler et réessayez.",
        .voiceErrorNoTime: "Je n'ai pas trouvé d'heure claire. Soyez plus précis.",
        .voiceErrorPermission: "Les notifications sont nécessaires. Autorisez-les dans Réglages.",
        .voiceErrorEmptyTitle: "Le titre de la tâche ne peut pas être vide.",
        .voiceErrorPermissions: "L'accès au microphone et à la reconnaissance vocale est requis.",
        .voiceErrorUnavailable: "La reconnaissance vocale n'est pas disponible pour cette langue. Vous pouvez saisir le texte.",
        .voiceErrorNoSpeech: "Aucune parole captée.",
        .voiceErrorMicrophone: "Impossible de démarrer le microphone.",
        .confirmationTask: "Tâche",
        .confirmationTitlePlaceholder: "Titre du rappel",
        .confirmationReminderTime: "Heure du rappel",
        .confirmationRepeat: "Répétition",
        .alertReminder: "Rappel",
        .alertGotIt: "Compris",
        .alertSnooze: "Rappeler dans 10 min",
        .alertSnoozeAction: "Dans 10 min",
        .alertSpeech: "Il est %1$@. %2$@. N'oubliez pas.",
        .paywallTitle: "Débloquer les rappels répétés",
        .paywallDescription: "Payez une fois et gardez les rappels quotidiens, hebdomadaires et mensuels pour toujours.",
        .paywallRestore: "Restaurer l'achat",
        .paywallClose: "Fermer",
        .paywallUnlockForever: "Débloquer pour toujours",
        .paywallUnlockPrice: "Débloquer pour toujours · %@",
        .purchaseNotAvailable: "Le produit Pro n'est pas encore disponible.",
        .purchasePending: "L'achat est en attente d'approbation.",
        .settingsTitle: "Réglages",
        .settingsLanguage: "Langue",
        .settingsAppLanguage: "Langue de l'app",
        .settingsLanguageFooter: "Utilisée pour l'interface, la reconnaissance vocale et les rappels parlés.",
        .settingsAlertStyle: "Style d'alerte",
        .settingsVoiceReading: "Lecture vocale",
        .settingsHapticPulse: "Vibration",
        .settingsScreenFlash: "Flash de l'écran",
        .settingsStrike: "Rappels insistants",
        .settingsEarlyMinutes: "Rappel %d min avant",
        .settingsVoiceVolume: "Volume vocal",
        .settingsPrivacy: "Confidentialité",
        .settingsClearAll: "Effacer toutes les données locales",
        .settingsPrivacyFooter: "Supprime les rappels, les notifications planifiées et les fichiers générés. Aucun compte n'est utilisé.",
        .settingsVersion: "Version",
        .settingsClearTitle: "Tout effacer ?",
        .settingsDeleteAll: "Tout supprimer",
        .settingsClearMessage: "Tous les rappels seront définitivement supprimés de cet appareil.",
        .addTitle: "Nouveau rappel",
        .addSaving: "Enregistrement…",
        .addNotificationsRequired: "Notifications requises",
        .addOpenSettings: "Ouvrir Réglages",
        .addNotificationMessage: "Autorisez les notifications pour être prévenu au bon moment.",
        .addSpeakOrType: "Parlez ou saisissez…",
        .addParseSentence: "Analyser la phrase",
        .addParsed: "Analysé : %@",
        .addListening: "Écoute…",
        .addReminderTitle: "Titre du rappel",
        .addNoteOptional: "Note (facultative)",
        .addWhatRemember: "Que faut-il retenir ?",
        .addRemindAt: "Rappeler à",
        .addWhen: "Quand",
        .addEndOn: "Fin le",
        .addRepeatOnceFooter: "Les rappels uniques sont supprimés un jour après expiration.",
        .addRepeatFooter: "Utilisez une date de fin pour un traitement de 7 jours par exemple.",
        .addStrikeEvery: "Rappeler toutes les 30 secondes",
        .addEarlyReminder: "Rappel anticipé",
        .addMinutes5: "5 minutes",
        .addMinutes10: "10 minutes",
        .addMinutes15: "15 minutes",
        .addPreviewVoice: "Écouter la voix",
        .addStopRecording: "Arrêter l'enregistrement",
        .addStartVoiceInput: "Démarrer la saisie vocale",
        .addPreviewSentence: "Ceci est un aperçu du rappel.",
        .notificationEarlyBody: "%@ (dans %d min)",
        .notificationEarlySpeech: "Votre rappel est à %1$@, dans %2$d minutes. %3$@."
    ]

    private static let german: [Key: String] = [
        .commonCancel: "Abbrechen",
        .commonDone: "Fertig",
        .commonSave: "Speichern",
        .commonCreate: "Erstellen",
        .commonClose: "Schließen",
        .commonNone: "Keine",
        .commonOK: "OK",
        .commonDelete: "Löschen",
        .commonEdit: "Bearbeiten",
        .commonOr: "oder",
        .appTitle: "Falls ich es vergesse",
        .homeEmptyTitle: "Keine Erinnerungen geplant",
        .homeEmptyDescription: "Sprich oder tippe eine einzeilige Erinnerung ein.",
        .homeToday: "Heute",
        .homeUpcoming: "Demnächst",
        .homeTomorrow: "Morgen",
        .homeDayAfterTomorrow: "Übermorgen",
        .homeExpired: "Abgelaufen",
        .homeNothingToday: "Heute nichts",
        .homeNothingLater: "Später nichts",
        .homeSpeak: "Sprechen",
        .homeType: "Tippen",
        .homeSettings: "Einstellungen",
        .homeVoiceA11y: "Erinnerung per Sprache erstellen",
        .homeVoiceHint: "Zum Sprechen gedrückt halten",
        .homeTypeA11y: "Erinnerung eingeben",
        .rowActionsHint: "Öffnet Bearbeiten und Löschen",
        .rowTimeUntil: "Zeit bis zur Erinnerung",
        .rowDueOverdue: "Jetzt fällig oder überfällig",
        .rowDueHour: "Innerhalb einer Stunde",
        .rowDueToday: "Heute",
        .rowDueWeek: "Diese Woche",
        .rowDueMonth: "Innerhalb eines Monats",
        .rowDueLater: "Mehr als einen Monat entfernt",
        .rowEarlyMinutes: "%d Min. vorher",
        .rowInMinutes: "in %d Min.",
        .rowLessThanMinute: "in weniger als einer Minute",
        .rowDueNow: "Jetzt fällig",
        .rowOverdueMinutes: "%d Min. überfällig",
        .rowOverdueHoursMinutes: "%d Std. %d Min. überfällig",
        .rowOverdueHours: "%d Std. überfällig",
        .rowNextOccurrence: "Nächstes: %@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "Einmal",
        .repeatDaily: "Täglich",
        .repeatWeekly: "Wöchentlich",
        .repeatMonthly: "Monatlich",
        .voiceListening: "Ich höre zu",
        .voiceProcessing: "Wird in Text umgewandelt",
        .voiceSummarizing: "Aufgabe wird zusammengefasst",
        .voiceCreated: "Erinnerung erstellt",
        .voiceUpdated: "Änderungen gespeichert",
        .voiceFailed: "Nicht abgeschlossen",
        .voiceListeningHint: "Erinnerung sprechen und dann loslassen",
        .voiceProcessingHint: "Sprache wird in Text umgewandelt",
        .voiceErrorNoTranscript: "Das habe ich nicht verstanden. Halte Sprechen gedrückt und versuche es erneut.",
        .voiceErrorNoTime: "Keine klare Erinnerungszeit erkannt. Bitte sei genauer.",
        .voiceErrorPermission: "Benachrichtigungen sind erforderlich. Erlaube sie in den Einstellungen.",
        .voiceErrorEmptyTitle: "Der Aufgabentitel darf nicht leer sein.",
        .voiceErrorPermissions: "Mikrofon- und Spracherkennungszugriff sind erforderlich.",
        .voiceErrorUnavailable: "Spracherkennung ist für diese Sprache nicht verfügbar. Du kannst weiter tippen.",
        .voiceErrorNoSpeech: "Es wurde keine Sprache erfasst.",
        .voiceErrorMicrophone: "Das Mikrofon konnte nicht gestartet werden.",
        .confirmationTask: "Aufgabe",
        .confirmationTitlePlaceholder: "Erinnerungstitel",
        .confirmationReminderTime: "Erinnerungszeit",
        .confirmationRepeat: "Wiederholen",
        .alertReminder: "Erinnerung",
        .alertGotIt: "Verstanden",
        .alertSnooze: "In 10 Min. erneut",
        .alertSnoozeAction: "In 10 Min.",
        .alertSpeech: "Es ist %1$@. %2$@. Nicht vergessen.",
        .paywallTitle: "Wiederkehrende Erinnerungen freischalten",
        .paywallDescription: "Einmal zahlen und tägliche, wöchentliche und monatliche Erinnerungen dauerhaft nutzen.",
        .paywallRestore: "Kauf wiederherstellen",
        .paywallClose: "Schließen",
        .paywallUnlockForever: "Dauerhaft freischalten",
        .paywallUnlockPrice: "Dauerhaft freischalten · %@",
        .purchaseNotAvailable: "Das Pro-Produkt ist noch nicht verfügbar.",
        .purchasePending: "Der Kauf wartet auf Genehmigung.",
        .settingsTitle: "Einstellungen",
        .settingsLanguage: "Sprache",
        .settingsAppLanguage: "App-Sprache",
        .settingsLanguageFooter: "Wird für Oberfläche, Spracherkennung und Sprachausgabe verwendet.",
        .settingsAlertStyle: "Benachrichtigungsstil",
        .settingsVoiceReading: "Sprachausgabe",
        .settingsHapticPulse: "Vibration",
        .settingsScreenFlash: "Bildschirmblitz",
        .settingsStrike: "Wiederholte Warnungen",
        .settingsEarlyMinutes: "%d Min. vorher erinnern",
        .settingsVoiceVolume: "Sprachlautstärke",
        .settingsPrivacy: "Datenschutz",
        .settingsClearAll: "Alle lokalen Daten löschen",
        .settingsPrivacyFooter: "Löscht Erinnerungen, geplante Benachrichtigungen und erzeugte Dateien. Kein Konto erforderlich.",
        .settingsVersion: "Version",
        .settingsClearTitle: "Alles löschen?",
        .settingsDeleteAll: "Alles löschen",
        .settingsClearMessage: "Alle Erinnerungen werden dauerhaft von diesem Gerät gelöscht.",
        .addTitle: "Neue Erinnerung",
        .addSaving: "Wird gespeichert…",
        .addNotificationsRequired: "Benachrichtigungen erforderlich",
        .addOpenSettings: "Einstellungen öffnen",
        .addNotificationMessage: "Erlaube Benachrichtigungen, damit Erinnerungen rechtzeitig ankommen.",
        .addSpeakOrType: "Sprechen oder tippen…",
        .addParseSentence: "Satz auswerten",
        .addParsed: "Erkannt: %@",
        .addListening: "Ich höre zu…",
        .addReminderTitle: "Erinnerungstitel",
        .addNoteOptional: "Notiz (optional)",
        .addWhatRemember: "Woran sollen wir denken?",
        .addRemindAt: "Erinnern um",
        .addWhen: "Wann",
        .addEndOn: "Endet am",
        .addRepeatOnceFooter: "Einmalige Erinnerungen werden einen Tag nach Ablauf entfernt.",
        .addRepeatFooter: "Nutze ein Enddatum für Aufgaben wie 7 Tage Medikamente.",
        .addStrikeEvery: "Alle 30 Sekunden erneut warnen",
        .addEarlyReminder: "Frühere Erinnerung",
        .addMinutes5: "5 Minuten",
        .addMinutes10: "10 Minuten",
        .addMinutes15: "15 Minuten",
        .addPreviewVoice: "Stimme anhören",
        .addStopRecording: "Aufnahme stoppen",
        .addStartVoiceInput: "Spracheingabe starten",
        .addPreviewSentence: "Dies ist eine Vorschau der Erinnerung.",
        .notificationEarlyBody: "%@ (in %d Min.)",
        .notificationEarlySpeech: "Deine Erinnerung ist um %1$@, in %2$d Minuten. %3$@."
    ]

    private static let turkish: [Key: String] = [
        .commonCancel: "İptal",
        .commonDone: "Bitti",
        .commonSave: "Kaydet",
        .commonCreate: "Oluştur",
        .commonClose: "Kapat",
        .commonNone: "Yok",
        .commonOK: "Tamam",
        .commonDelete: "Sil",
        .commonEdit: "Düzenle",
        .commonOr: "veya",
        .appTitle: "Unutursam diye",
        .homeEmptyTitle: "Planlanmış hatırlatma yok",
        .homeEmptyDescription: "Konuşun veya tek satırlık bir hatırlatma yazın.",
        .homeToday: "Bugün",
        .homeUpcoming: "Yaklaşan",
        .homeTomorrow: "Yarın",
        .homeDayAfterTomorrow: "Öbür gün",
        .homeExpired: "Süresi geçti",
        .homeNothingToday: "Bugün bir şey yok",
        .homeNothingLater: "Sonrasında bir şey yok",
        .homeSpeak: "Konuş",
        .homeType: "Yaz",
        .homeSettings: "Ayarlar",
        .homeVoiceA11y: "Sesle hatırlatma oluştur",
        .homeVoiceHint: "Konuşmak için basılı tut",
        .homeTypeA11y: "Hatırlatma yaz",
        .rowActionsHint: "Düzenleme ve silme işlemlerini açar",
        .rowTimeUntil: "Hatırlatmaya kalan süre",
        .rowDueOverdue: "Şimdi veya gecikmiş",
        .rowDueHour: "Bir saat içinde",
        .rowDueToday: "Bugün",
        .rowDueWeek: "Bu hafta",
        .rowDueMonth: "Bir ay içinde",
        .rowDueLater: "Bir aydan uzak",
        .rowEarlyMinutes: "%d dk önce",
        .rowInMinutes: "%d dk sonra",
        .rowLessThanMinute: "bir dakikadan kısa sürede",
        .rowDueNow: "Şimdi zamanı",
        .rowOverdueMinutes: "%d dk gecikti",
        .rowOverdueHoursMinutes: "%d sa %d dk gecikti",
        .rowOverdueHours: "%d sa gecikti",
        .rowNextOccurrence: "Sonraki: %@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "Bir kez",
        .repeatDaily: "Günlük",
        .repeatWeekly: "Haftalık",
        .repeatMonthly: "Aylık",
        .voiceListening: "Dinliyorum",
        .voiceProcessing: "Metne dönüştürülüyor",
        .voiceSummarizing: "Görev özetleniyor",
        .voiceCreated: "Hatırlatma oluşturuldu",
        .voiceUpdated: "Değişiklikler kaydedildi",
        .voiceFailed: "Tamamlanmadı",
        .voiceListeningHint: "Hatırlatmayı söyleyin ve bırakın",
        .voiceProcessingHint: "Konuşmanız metne dönüştürülüyor",
        .voiceErrorNoTranscript: "Anlayamadım. Konuş düğmesini basılı tutup tekrar deneyin.",
        .voiceErrorNoTime: "Net bir hatırlatma saati bulamadım. Lütfen daha açık söyleyin.",
        .voiceErrorPermission: "Bildirim izni gerekli. Hatırlatma oluşturmak için Ayarlar'dan izin verin.",
        .voiceErrorEmptyTitle: "Görev başlığı boş olamaz.",
        .voiceErrorPermissions: "Mikrofon ve konuşma tanıma izni gerekli.",
        .voiceErrorUnavailable: "Bu dil için konuşma tanıma kullanılamıyor. Yine de yazabilirsiniz.",
        .voiceErrorNoSpeech: "Ses algılanamadı.",
        .voiceErrorMicrophone: "Mikrofon başlatılamadı.",
        .confirmationTask: "Görev",
        .confirmationTitlePlaceholder: "Hatırlatma başlığı",
        .confirmationReminderTime: "Hatırlatma saati",
        .confirmationRepeat: "Tekrar",
        .alertReminder: "Hatırlatma",
        .alertGotIt: "Anladım",
        .alertSnooze: "10 dk sonra",
        .alertSnoozeAction: "10 dk sonra",
        .alertSpeech: "Saat %1$@. %2$@. Unutma.",
        .paywallTitle: "Tekrarlanan hatırlatmaların kilidini aç",
        .paywallDescription: "Bir kez öde, günlük, haftalık ve aylık hatırlatmaları kalıcı olarak kullan.",
        .paywallRestore: "Satın alımı geri yükle",
        .paywallClose: "Kapat",
        .paywallUnlockForever: "Kalıcı olarak aç",
        .paywallUnlockPrice: "Kalıcı olarak aç · %@",
        .purchaseNotAvailable: "Pro ürün henüz kullanılamıyor.",
        .purchasePending: "Satın alma onay bekliyor.",
        .settingsTitle: "Ayarlar",
        .settingsLanguage: "Dil",
        .settingsAppLanguage: "Uygulama dili",
        .settingsLanguageFooter: "Arayüz, konuşma tanıma ve sesli hatırlatmalar için kullanılır.",
        .settingsAlertStyle: "Uyarı biçimi",
        .settingsVoiceReading: "Sesli okuma",
        .settingsHapticPulse: "Titreşim",
        .settingsScreenFlash: "Ekran flaşı",
        .settingsStrike: "Israrcı hatırlatma",
        .settingsEarlyMinutes: "%d dk önce hatırlat",
        .settingsVoiceVolume: "Ses düzeyi",
        .settingsPrivacy: "Gizlilik",
        .settingsClearAll: "Tüm yerel verileri temizle",
        .settingsPrivacyFooter: "Hatırlatmaları, planlanmış bildirimleri ve üretilen dosyaları siler. Hesap kullanılmaz.",
        .settingsVersion: "Sürüm",
        .settingsClearTitle: "Her şey silinsin mi?",
        .settingsDeleteAll: "Tümünü sil",
        .settingsClearMessage: "Tüm hatırlatmalar bu cihazdan kalıcı olarak silinecek.",
        .addTitle: "Yeni Hatırlatma",
        .addSaving: "Kaydediliyor…",
        .addNotificationsRequired: "Bildirimler gerekli",
        .addOpenSettings: "Ayarları Aç",
        .addNotificationMessage: "Hatırlatmaların zamanında gelmesi için bildirimlere izin verin.",
        .addSpeakOrType: "Konuş veya yaz…",
        .addParseSentence: "Cümleyi çözümle",
        .addParsed: "Çözümlendi: %@",
        .addListening: "Dinliyorum…",
        .addReminderTitle: "Hatırlatma başlığı",
        .addNoteOptional: "Not (isteğe bağlı)",
        .addWhatRemember: "Neyi hatırlayalım?",
        .addRemindAt: "Hatırlatma zamanı",
        .addWhen: "Ne zaman",
        .addEndOn: "Bitiş",
        .addRepeatOnceFooter: "Tek seferlik hatırlatıcılar süresi geçtikten bir gün sonra silinir.",
        .addRepeatFooter: "7 günlük ilaç gibi görevler için bitiş tarihi kullanın.",
        .addStrikeEvery: "Her 30 saniyede tekrar uyar",
        .addEarlyReminder: "Erken hatırlatma",
        .addMinutes5: "5 dakika",
        .addMinutes10: "10 dakika",
        .addMinutes15: "15 dakika",
        .addPreviewVoice: "Sesi önizle",
        .addStopRecording: "Kaydı durdur",
        .addStartVoiceInput: "Sesli girişi başlat",
        .addPreviewSentence: "Bu bir hatırlatma önizlemesidir.",
        .notificationEarlyBody: "%@ (%d dk içinde)",
        .notificationEarlySpeech: "Hatırlatman %1$@, %2$d dakika içinde. %3$@."
    ]

    private static let spanish: [Key: String] = [
        .commonCancel: "Cancelar",
        .commonDone: "Listo",
        .commonSave: "Guardar",
        .commonCreate: "Crear",
        .commonClose: "Cerrar",
        .commonNone: "Ninguno",
        .commonOK: "OK",
        .commonDelete: "Eliminar",
        .commonEdit: "Editar",
        .commonOr: "o",
        .appTitle: "En caso de que olvide",
        .homeEmptyTitle: "No hay recordatorios programados",
        .homeEmptyDescription: "Habla o escribe un recordatorio de una línea.",
        .homeToday: "Hoy",
        .homeUpcoming: "Próximos",
        .homeTomorrow: "Mañana",
        .homeDayAfterTomorrow: "Pasado mañana",
        .homeExpired: "Vencido",
        .homeNothingToday: "Nada para hoy",
        .homeNothingLater: "Nada más adelante",
        .homeSpeak: "Hablar",
        .homeType: "Escribir",
        .homeSettings: "Ajustes",
        .homeVoiceA11y: "Crear recordatorio por voz",
        .homeVoiceHint: "Mantén pulsado para hablar",
        .homeTypeA11y: "Escribir un recordatorio",
        .rowActionsHint: "Abre las acciones de edición y eliminación",
        .rowTimeUntil: "Tiempo hasta el recordatorio",
        .rowDueOverdue: "Ahora o vencido",
        .rowDueHour: "En menos de una hora",
        .rowDueToday: "Hoy",
        .rowDueWeek: "Esta semana",
        .rowDueMonth: "En menos de un mes",
        .rowDueLater: "En más de un mes",
        .rowEarlyMinutes: "%d min antes",
        .rowInMinutes: "en %d min",
        .rowLessThanMinute: "en menos de un minuto",
        .rowDueNow: "Vence ahora",
        .rowOverdueMinutes: "%d min de retraso",
        .rowOverdueHoursMinutes: "%d h %d min de retraso",
        .rowOverdueHours: "%d h de retraso",
        .rowNextOccurrence: "Siguiente: %@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "Una vez",
        .repeatDaily: "Diario",
        .repeatWeekly: "Semanal",
        .repeatMonthly: "Mensual",
        .voiceListening: "Escuchando",
        .voiceProcessing: "Convirtiendo a texto",
        .voiceSummarizing: "Resumiendo tarea",
        .voiceCreated: "Recordatorio creado",
        .voiceUpdated: "Cambios guardados",
        .voiceFailed: "No completado",
        .voiceListeningHint: "Di tu recordatorio y suelta",
        .voiceProcessingHint: "Convirtiendo tu voz a texto",
        .voiceErrorNoTranscript: "No te entendí. Mantén Hablar y vuelve a intentarlo.",
        .voiceErrorNoTime: "No encontré una hora clara. Sé más específico.",
        .voiceErrorPermission: "Se requieren notificaciones. Permítelas en Ajustes.",
        .voiceErrorEmptyTitle: "El título de la tarea no puede estar vacío.",
        .voiceErrorPermissions: "Se requieren permisos de micrófono y reconocimiento de voz.",
        .voiceErrorUnavailable: "El reconocimiento de voz no está disponible para este idioma. Aún puedes escribir.",
        .voiceErrorNoSpeech: "No se captó voz.",
        .voiceErrorMicrophone: "No se pudo iniciar el micrófono.",
        .confirmationTask: "Tarea",
        .confirmationTitlePlaceholder: "Título del recordatorio",
        .confirmationReminderTime: "Hora del recordatorio",
        .confirmationRepeat: "Repetir",
        .alertReminder: "Recordatorio",
        .alertGotIt: "Entendido",
        .alertSnooze: "Posponer 10 min",
        .alertSnoozeAction: "En 10 min",
        .alertSpeech: "Son las %1$@. %2$@. No lo olvides.",
        .paywallTitle: "Desbloquear recordatorios repetidos",
        .paywallDescription: "Paga una vez y conserva para siempre los recordatorios diarios, semanales y mensuales.",
        .paywallRestore: "Restaurar compra",
        .paywallClose: "Cerrar",
        .paywallUnlockForever: "Desbloquear para siempre",
        .paywallUnlockPrice: "Desbloquear para siempre · %@",
        .purchaseNotAvailable: "El producto Pro aún no está disponible.",
        .purchasePending: "La compra está pendiente de aprobación.",
        .settingsTitle: "Ajustes",
        .settingsLanguage: "Idioma",
        .settingsAppLanguage: "Idioma de la app",
        .settingsLanguageFooter: "Se usa para la interfaz, el reconocimiento de voz y los recordatorios hablados.",
        .settingsAlertStyle: "Estilo de alerta",
        .settingsVoiceReading: "Lectura por voz",
        .settingsHapticPulse: "Vibración",
        .settingsScreenFlash: "Destello de pantalla",
        .settingsStrike: "Recordatorios insistentes",
        .settingsEarlyMinutes: "Avisar %d min antes",
        .settingsVoiceVolume: "Volumen de voz",
        .settingsPrivacy: "Privacidad",
        .settingsClearAll: "Borrar todos los datos locales",
        .settingsPrivacyFooter: "Elimina recordatorios, notificaciones programadas y archivos generados. No se usa cuenta.",
        .settingsVersion: "Versión",
        .settingsClearTitle: "¿Borrar todo?",
        .settingsDeleteAll: "Eliminar todo",
        .settingsClearMessage: "Todos los recordatorios se eliminarán permanentemente de este dispositivo.",
        .addTitle: "Nuevo recordatorio",
        .addSaving: "Guardando…",
        .addNotificationsRequired: "Se requieren notificaciones",
        .addOpenSettings: "Abrir Ajustes",
        .addNotificationMessage: "Permite notificaciones para que los recordatorios lleguen a tiempo.",
        .addSpeakOrType: "Habla o escribe…",
        .addParseSentence: "Analizar frase",
        .addParsed: "Analizado: %@",
        .addListening: "Escuchando…",
        .addReminderTitle: "Título del recordatorio",
        .addNoteOptional: "Nota (opcional)",
        .addWhatRemember: "¿Qué debemos recordar?",
        .addRemindAt: "Recordar a las",
        .addWhen: "Cuándo",
        .addEndOn: "Termina el",
        .addRepeatOnceFooter: "Los recordatorios únicos se eliminan un día después de vencer.",
        .addRepeatFooter: "Usa una fecha de fin para tareas como medicación durante 7 días.",
        .addStrikeEvery: "Volver a avisar cada 30 segundos",
        .addEarlyReminder: "Recordatorio anticipado",
        .addMinutes5: "5 minutos",
        .addMinutes10: "10 minutos",
        .addMinutes15: "15 minutos",
        .addPreviewVoice: "Escuchar voz",
        .addStopRecording: "Detener grabación",
        .addStartVoiceInput: "Iniciar entrada de voz",
        .addPreviewSentence: "Esta es una vista previa del recordatorio.",
        .notificationEarlyBody: "%@ (en %d min)",
        .notificationEarlySpeech: "Tu recordatorio es a las %1$@, en %2$d minutos. %3$@."
    ]

    private static let portuguese: [Key: String] = [
        .commonCancel: "Cancelar",
        .commonDone: "Concluído",
        .commonSave: "Salvar",
        .commonCreate: "Criar",
        .commonClose: "Fechar",
        .commonNone: "Nenhum",
        .commonOK: "OK",
        .commonDelete: "Excluir",
        .commonEdit: "Editar",
        .commonOr: "ou",
        .appTitle: "Caso eu esqueça",
        .homeEmptyTitle: "Nenhum lembrete agendado",
        .homeEmptyDescription: "Fale ou digite um lembrete de uma linha.",
        .homeToday: "Hoje",
        .homeUpcoming: "Próximos",
        .homeTomorrow: "Amanhã",
        .homeDayAfterTomorrow: "Depois de amanhã",
        .homeExpired: "Expirado",
        .homeNothingToday: "Nada hoje",
        .homeNothingLater: "Nada depois",
        .homeSpeak: "Falar",
        .homeType: "Digitar",
        .homeSettings: "Ajustes",
        .homeVoiceA11y: "Criar lembrete por voz",
        .homeVoiceHint: "Mantenha pressionado para falar",
        .homeTypeA11y: "Digitar um lembrete",
        .rowActionsHint: "Abre ações de edição e exclusão",
        .rowTimeUntil: "Tempo até o lembrete",
        .rowDueOverdue: "Agora ou atrasado",
        .rowDueHour: "Em menos de uma hora",
        .rowDueToday: "Hoje",
        .rowDueWeek: "Esta semana",
        .rowDueMonth: "Em menos de um mês",
        .rowDueLater: "Em mais de um mês",
        .rowEarlyMinutes: "%d min antes",
        .rowInMinutes: "em %d min",
        .rowLessThanMinute: "em menos de um minuto",
        .rowDueNow: "Vence agora",
        .rowOverdueMinutes: "%d min de atraso",
        .rowOverdueHoursMinutes: "%d h %d min de atraso",
        .rowOverdueHours: "%d h de atraso",
        .rowNextOccurrence: "Próximo: %@",
        .rowDayAndTime: "%1$@ %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "Uma vez",
        .repeatDaily: "Diário",
        .repeatWeekly: "Semanal",
        .repeatMonthly: "Mensal",
        .voiceListening: "Ouvindo",
        .voiceProcessing: "Convertendo para texto",
        .voiceSummarizing: "Resumindo tarefa",
        .voiceCreated: "Lembrete criado",
        .voiceUpdated: "Alterações salvas",
        .voiceFailed: "Não concluído",
        .voiceListeningHint: "Diga o lembrete e solte",
        .voiceProcessingHint: "Convertendo sua fala em texto",
        .voiceErrorNoTranscript: "Não entendi. Mantenha Falar pressionado e tente de novo.",
        .voiceErrorNoTime: "Não encontrei um horário claro. Seja mais específico.",
        .voiceErrorPermission: "Notificações são necessárias. Permita nos Ajustes.",
        .voiceErrorEmptyTitle: "O título da tarefa não pode ficar vazio.",
        .voiceErrorPermissions: "Permissões de microfone e reconhecimento de fala são necessárias.",
        .voiceErrorUnavailable: "O reconhecimento de fala não está disponível para este idioma. Você ainda pode digitar.",
        .voiceErrorNoSpeech: "Nenhuma fala foi capturada.",
        .voiceErrorMicrophone: "Não foi possível iniciar o microfone.",
        .confirmationTask: "Tarefa",
        .confirmationTitlePlaceholder: "Título do lembrete",
        .confirmationReminderTime: "Horário do lembrete",
        .confirmationRepeat: "Repetir",
        .alertReminder: "Lembrete",
        .alertGotIt: "Entendi",
        .alertSnooze: "Adiar 10 min",
        .alertSnoozeAction: "Em 10 min",
        .alertSpeech: "São %1$@. %2$@. Não esqueça.",
        .paywallTitle: "Desbloquear lembretes repetidos",
        .paywallDescription: "Pague uma vez e mantenha lembretes diários, semanais e mensais para sempre.",
        .paywallRestore: "Restaurar compra",
        .paywallClose: "Fechar",
        .paywallUnlockForever: "Desbloquear para sempre",
        .paywallUnlockPrice: "Desbloquear para sempre · %@",
        .purchaseNotAvailable: "O produto Pro ainda não está disponível.",
        .purchasePending: "A compra está aguardando aprovação.",
        .settingsTitle: "Ajustes",
        .settingsLanguage: "Idioma",
        .settingsAppLanguage: "Idioma do app",
        .settingsLanguageFooter: "Usado na interface, no reconhecimento de fala e nos lembretes falados.",
        .settingsAlertStyle: "Estilo do alerta",
        .settingsVoiceReading: "Leitura por voz",
        .settingsHapticPulse: "Vibração",
        .settingsScreenFlash: "Flash da tela",
        .settingsStrike: "Lembretes insistentes",
        .settingsEarlyMinutes: "Avisar %d min antes",
        .settingsVoiceVolume: "Volume da voz",
        .settingsPrivacy: "Privacidade",
        .settingsClearAll: "Apagar todos os dados locais",
        .settingsPrivacyFooter: "Remove lembretes, notificações agendadas e arquivos gerados. Nenhuma conta é usada.",
        .settingsVersion: "Versão",
        .settingsClearTitle: "Apagar tudo?",
        .settingsDeleteAll: "Apagar tudo",
        .settingsClearMessage: "Todos os lembretes serão apagados permanentemente deste dispositivo.",
        .addTitle: "Novo lembrete",
        .addSaving: "Salvando…",
        .addNotificationsRequired: "Notificações são necessárias",
        .addOpenSettings: "Abrir Ajustes",
        .addNotificationMessage: "Permita notificações para que os lembretes cheguem na hora certa.",
        .addSpeakOrType: "Fale ou digite…",
        .addParseSentence: "Analisar frase",
        .addParsed: "Analisado: %@",
        .addListening: "Ouvindo…",
        .addReminderTitle: "Título do lembrete",
        .addNoteOptional: "Nota (opcional)",
        .addWhatRemember: "O que devemos lembrar?",
        .addRemindAt: "Lembrar às",
        .addWhen: "Quando",
        .addEndOn: "Termina em",
        .addRepeatOnceFooter: "Lembretes únicos são removidos um dia após vencerem.",
        .addRepeatFooter: "Use uma data final para tarefas como medicamento por 7 dias.",
        .addStrikeEvery: "Avisar novamente a cada 30 segundos",
        .addEarlyReminder: "Lembrete antecipado",
        .addMinutes5: "5 minutos",
        .addMinutes10: "10 minutos",
        .addMinutes15: "15 minutos",
        .addPreviewVoice: "Prévia da voz",
        .addStopRecording: "Parar gravação",
        .addStartVoiceInput: "Iniciar entrada de voz",
        .addPreviewSentence: "Esta é uma prévia do lembrete.",
        .notificationEarlyBody: "%@ (em %d min)",
        .notificationEarlySpeech: "Seu lembrete é às %1$@, em %2$d minutos. %3$@."
    ]

    private static let russian: [Key: String] = [
        .commonCancel: "Отмена",
        .commonDone: "Готово",
        .commonSave: "Сохранить",
        .commonCreate: "Создать",
        .commonClose: "Закрыть",
        .commonNone: "Нет",
        .commonOK: "ОК",
        .commonDelete: "Удалить",
        .commonEdit: "Изменить",
        .commonOr: "или",
        .appTitle: "Если я забуду",
        .homeEmptyTitle: "Нет запланированных напоминаний",
        .homeEmptyDescription: "Скажите или введите напоминание одной строкой.",
        .homeToday: "Сегодня",
        .homeUpcoming: "Далее",
        .homeTomorrow: "Завтра",
        .homeDayAfterTomorrow: "Послезавтра",
        .homeExpired: "Просрочено",
        .homeNothingToday: "Сегодня ничего нет",
        .homeNothingLater: "Позже ничего нет",
        .homeSpeak: "Говорить",
        .homeType: "Ввести",
        .homeSettings: "Настройки",
        .homeVoiceA11y: "Создать напоминание голосом",
        .homeVoiceHint: "Удерживайте, чтобы говорить",
        .homeTypeA11y: "Ввести напоминание",
        .rowActionsHint: "Открывает действия изменения и удаления",
        .rowTimeUntil: "Время до напоминания",
        .rowDueOverdue: "Сейчас или просрочено",
        .rowDueHour: "В течение часа",
        .rowDueToday: "Сегодня",
        .rowDueWeek: "На этой неделе",
        .rowDueMonth: "В течение месяца",
        .rowDueLater: "Больше чем через месяц",
        .rowEarlyMinutes: "За %d мин",
        .rowInMinutes: "через %d мин",
        .rowLessThanMinute: "менее чем через минуту",
        .rowDueNow: "Срок сейчас",
        .rowOverdueMinutes: "просрочено на %d мин",
        .rowOverdueHoursMinutes: "просрочено на %d ч %d мин",
        .rowOverdueHours: "просрочено на %d ч",
        .rowNextOccurrence: "Далее: %@",
        .rowDayAndTime: "%1$@, %2$@",
        .rowCountdownAndTime: "%1$@ · %2$@",
        .repeatOnce: "Один раз",
        .repeatDaily: "Ежедневно",
        .repeatWeekly: "Еженедельно",
        .repeatMonthly: "Ежемесячно",
        .voiceListening: "Слушаю",
        .voiceProcessing: "Преобразование в текст",
        .voiceSummarizing: "Обобщение задачи",
        .voiceCreated: "Напоминание создано",
        .voiceUpdated: "Изменения сохранены",
        .voiceFailed: "Не завершено",
        .voiceListeningHint: "Скажите напоминание и отпустите",
        .voiceProcessingHint: "Преобразование речи в текст",
        .voiceErrorNoTranscript: "Я не расслышал. Удерживайте «Говорить» и повторите.",
        .voiceErrorNoTime: "Не удалось найти точное время. Скажите конкретнее.",
        .voiceErrorPermission: "Нужно разрешение на уведомления. Разрешите его в Настройках.",
        .voiceErrorEmptyTitle: "Название задачи не может быть пустым.",
        .voiceErrorPermissions: "Нужны разрешения для микрофона и распознавания речи.",
        .voiceErrorUnavailable: "Распознавание речи недоступно для этого языка. Можно ввести текст.",
        .voiceErrorNoSpeech: "Речь не была записана.",
        .voiceErrorMicrophone: "Не удалось запустить микрофон.",
        .confirmationTask: "Задача",
        .confirmationTitlePlaceholder: "Название напоминания",
        .confirmationReminderTime: "Время напоминания",
        .confirmationRepeat: "Повтор",
        .alertReminder: "Напоминание",
        .alertGotIt: "Понятно",
        .alertSnooze: "Через 10 мин",
        .alertSnoozeAction: "Через 10 мин",
        .alertSpeech: "Сейчас %1$@. %2$@. Не забудьте.",
        .paywallTitle: "Открыть повторяющиеся напоминания",
        .paywallDescription: "Оплатите один раз и пользуйтесь ежедневными, еженедельными и ежемесячными напоминаниями навсегда.",
        .paywallRestore: "Восстановить покупку",
        .paywallClose: "Закрыть",
        .paywallUnlockForever: "Открыть навсегда",
        .paywallUnlockPrice: "Открыть навсегда · %@",
        .purchaseNotAvailable: "Продукт Pro пока недоступен.",
        .purchasePending: "Покупка ожидает подтверждения.",
        .settingsTitle: "Настройки",
        .settingsLanguage: "Язык",
        .settingsAppLanguage: "Язык приложения",
        .settingsLanguageFooter: "Используется для интерфейса, распознавания речи и голосовых напоминаний.",
        .settingsAlertStyle: "Стиль оповещений",
        .settingsVoiceReading: "Голосовое чтение",
        .settingsHapticPulse: "Вибрация",
        .settingsScreenFlash: "Вспышка экрана",
        .settingsStrike: "Настойчивые напоминания",
        .settingsEarlyMinutes: "Напомнить за %d мин",
        .settingsVoiceVolume: "Громкость голоса",
        .settingsPrivacy: "Конфиденциальность",
        .settingsClearAll: "Удалить все локальные данные",
        .settingsPrivacyFooter: "Удаляет напоминания, запланированные уведомления и созданные файлы. Аккаунт не используется.",
        .settingsVersion: "Версия",
        .settingsClearTitle: "Удалить всё?",
        .settingsDeleteAll: "Удалить всё",
        .settingsClearMessage: "Все напоминания будут навсегда удалены с этого устройства.",
        .addTitle: "Новое напоминание",
        .addSaving: "Сохранение…",
        .addNotificationsRequired: "Нужны уведомления",
        .addOpenSettings: "Открыть Настройки",
        .addNotificationMessage: "Разрешите уведомления, чтобы напоминания приходили вовремя.",
        .addSpeakOrType: "Говорите или введите…",
        .addParseSentence: "Разобрать фразу",
        .addParsed: "Разобрано: %@",
        .addListening: "Слушаю…",
        .addReminderTitle: "Название напоминания",
        .addNoteOptional: "Заметка (необязательно)",
        .addWhatRemember: "Что запомнить?",
        .addRemindAt: "Напомнить в",
        .addWhen: "Когда",
        .addEndOn: "Закончить",
        .addRepeatOnceFooter: "Одноразовые напоминания удаляются через день после истечения срока.",
        .addRepeatFooter: "Укажите дату окончания для задач вроде 7 дней приёма лекарств.",
        .addStrikeEvery: "Повторять каждые 30 секунд",
        .addEarlyReminder: "Раннее напоминание",
        .addMinutes5: "5 минут",
        .addMinutes10: "10 минут",
        .addMinutes15: "15 минут",
        .addPreviewVoice: "Прослушать голос",
        .addStopRecording: "Остановить запись",
        .addStartVoiceInput: "Начать голосовой ввод",
        .addPreviewSentence: "Это предпросмотр напоминания.",
        .notificationEarlyBody: "%@ (через %d мин)",
        .notificationEarlySpeech: "Напоминание в %1$@, через %2$d мин. %3$@."
    ]
}
